<!doctype html>
<html>
<head>
    <title>Задание 4</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<section>
    <div class="container">
        <header>
            <?php include __DIR__ . '/components/menu.phtml'; ?>
        </header>
        <p>
            Дан массив $mas = [4, 5, 1, 4, 7, 8, 15, 6, 71, 45, 2]; сделайте алгоритм и найдите сумму между
            минимальным и максимальными значениями. Не используя готовые функции.
        </p>
        <ul>
            <li>
                Используя цикл
            </li>
            <li>
                Используйте один цикл, в один проход**
            </li>
        </ul>
        <pre>
            $array = [4, 5, 1, 4, 7, 8, 15, 6, 71, 45, 2];

            $valueMax = PHP_INT_MIN;
            $valueMin = PHP_INT_MAX;

            for ($i = 0; $i < count($array); $i++) {
                if ($array[$i] > $valueMax) {
                    $valueMax = $array[$i];
                }
                if ($valueMin > $array[$i]) {
                    $valueMin = $array[$i];
                }
            }

            echo $valueMax + $valueMin;
        </pre>
    </div>
</section>
</body>
</html>