<!doctype html>
<html>
<head>
    <title>Главная</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<div class="container">
    <header>
        <?php include __DIR__ . '/components/menu.phtml'; ?>
    </header>
    <main>
        <h1>Добро пожаловать!</h1>
        <p>Используйте меню для перехода к заданиям</p>
        <a target="_blank" href="https://github.com/Juice2597/top-academy-php">GitHub</a>
    </main>
</div>
</body>
</html>