<!doctype html>
<html>
<head>
    <title>Задание 1</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<section>
    <div class="container">
        <header>
            <?php include __DIR__ . '/components/menu.phtml'; ?>
        </header>
        <p>
            Подготовьте массив целых чисел (4, 5, 1, 4, 7, 8, 15, 6, 71, 45, 2)
            Сделайте функцию, которая по этому массиву вернет новый массив, в котором каждое значение
            будет заменено строкой "четное" или "не четное". ["четное", "не четное"...] evenOdd()
        </p>
        <ul>
            <li>
                Сделать через цикл
            </li>
            <li>
                Сделать через array_map*
            </li>
        </ul>
        <pre>
            $array = [4, 5, 1, 4, 7, 8, 15, 6, 71, 45, 2];
            $evenOdd = [];

            for ($i = 0; $i < count($array); $i++) {
                if ($array[$i] % 2 == 0) {
                    array_push($evenOdd, 'четное');
                } else {
                    array_push($evenOdd, 'нечетное');
                }
            }
            print_r($evenOdd);

            /**
             * 2 Вариант
             */

            $twoEvenOdd = [];
            $twoEvenOdd = array_map(fn($n) => $n % 2 == 0 ? 'четное' : 'нечетное', $array);
            print_r($twoEvenOdd);
        </pre>
    </div>
</section>
</body>
</html>