<nav>
    <a href="<?=BASE_URL?>">Главная</a>
    <a href="<?=BASE_URL?>?page=calculate">Калькулятор</a>
    <a href="<?=BASE_URL?>?page=increment">Сложение</a>
    <a href="<?=BASE_URL?>?page=decrement">Вычитание</a>
    <a href="<?=BASE_URL?>?page=multiply">Умножение</a>
    <a href="<?=BASE_URL?>?page=divide">Деление</a>
    <a href="<?=BASE_URL?>?page=add-post">Добавить пост</a>
    <a href="<?=BASE_URL?>?page=post-list">Список постов</a>
</nav>