<section class="add-post">
    <h2>Создать пост</h2>
    <form method="post">
        <div class="block-add">
            <div>
                <label for="name">Заголовок поста</label>
                <input type="text" name="name" required>
            </div>
            <div>
                <select name="category">
                    <option value="1">Спорт</option>
                    <option value="2">Политика</option>
                </select>
            </div>
            <div>
                <label for="title">Текст поста</label>
                <textarea type="text" name="title" required></textarea>
            </div>
            <button>Создать пост</button>
        </div>

    </form>
</section>