<?php $posts = json_decode(file_get_contents(__DIR__ . "/../db.json"), true) ?? []; ?>

<h2>Список всех постов</h2>
<nav>
    <a href="?page=category&id=1">Посты о спорте</a>
    <a href="?page=category&id=2">Посты о политике</a>
</nav>

<?php foreach ($posts as ['name' => $name, 'title' => $title, 'category' => $category, 'id' => $id]) : ?>
    <div class="block-post">
        <span><?= $category == '1' ? 'Посты о спорте' : 'Посты о политике' ?></span>
        <h2><?= $name ?></h2>
        <p><?= $title ?></p>
    </div>
<?php endforeach; ?>

